# Generated by Django 4.0.3 on 2022-03-14 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_animations_id_alter_music_id_alter_photo_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animations',
            new_name='Animation',
        ),
    ]
