# Generated by Django 4.0.3 on 2022-03-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_rename_animations_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animation',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='music',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='simulation',
            name='main',
            field=models.BooleanField(default=False),
        ),
    ]
